[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200

[functions]
  directory = "netlify/functions"

# 🔔 reminders
[functions.send-reminders]
  schedule = "*/5 * * * *"

# ⏱ auto cancel
[functions.auto-cancel]
  schedule = "*/5 * * * *"

# 🎂 birthdays
[functions.birthdays]
  schedule = "30 13 * * *"